name: Upload to Azure Storage

on:
    workflow_dispatch:

jobs:
    upload:
        runs-on: ubuntu-latest

        steps:
        # Check out and get latest version of repo
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Azure Login action
            uses: azure/login@v2
            with:
             creds: ${{ secrets.AZURE_CREDENTIALS }}
             enable-AzPSSession: true
