name: Upload to Azure Storage

on:
    workflow_dispatch:

jobs:
    upload:
        runs-on: ubuntu-latest

        steps:
        # Check out and get latest version of repo
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Set up Azure CLI
            uses: azure/login@v1
            with:
                creds: ${{ secrets.AZURECRIDENTIALS }}
