name: Upload to Azure Storage

on:
    workflow_dispatch:

jobs:
    upload:
        runs-on: ubuntu-latest

        steps:
          - uses: azure/login@v2
            with:
              creds: '{"clientId":"${{ secrets.AZURE_CREDENTIALS_CLIENTID }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_CREDENTIALS_CLIENT_SUBSCRIPTIONID }}","tenantId":"${{ secrets.AZURE_CREDENTIALS_CLIENT_TENANTID }}"}'
          
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Azure Login action
            uses: azure/login@v2
            with:
             creds: ${{ secrets.AZURE_CREDENTIALS }}
             enable-AzPSSession: true
